// Generated by Bisonc++ V4.01.00 on Tue, 12 Mar 2013 13:23:36 +0100

// $insert class.ih
#include "ccparser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {290, 0}, // 1: stmt_list ->  <empty>
     {290, 2}, // 2: stmt_list ->  stmt_list stmt
     {291, 1}, // 3: stmt ->  io_stmt
     {291, 1}, // 4: stmt ->  expr_stmt
     {291, 1}, // 5: stmt ->  if_stmt
     {291, 1}, // 6: stmt ->  for_stmt
     {291, 3}, // 7: stmt ('{') ->  '{' stmt_list '}'
     {293, 2}, // 8: expr_stmt (';') ->  expr ';'
     {292, 3}, // 9: io_stmt (PRINTC) ->  PRINTC expr ';'
     {292, 3}, // 10: io_stmt (PRINTD) ->  PRINTD expr ';'
     {292, 3}, // 11: io_stmt (PRINTS) ->  PRINTS expr ';'
     {292, 3}, // 12: io_stmt (SCAN) ->  SCAN lvalue ';'
     {294, 2}, // 13: if_stmt ->  if stmt
     {294, 4}, // 14: if_stmt ->  if stmt else stmt
     {295, 2}, // 15: for_stmt ->  for stmt
     {296, 2}, // 16: if (IF) ->  IF expr
     {297, 1}, // 17: else (ELSE) ->  ELSE
     {298, 6}, // 18: for (FOR) ->  FOR lvalue '=' expr ':' expr
     {298, 8}, // 19: for (FOR) ->  FOR lvalue '=' expr ':' expr ':' expr
     {299, 1}, // 20: opt_list ->  list
     {299, 0}, // 21: opt_list ->  <empty>
     {300, 1}, // 22: list ->  expr
     {300, 3}, // 23: list (',') ->  list ',' expr
     {301, 1}, // 24: rvalue (CST) ->  CST
     {301, 1}, // 25: rvalue (CHR) ->  CHR
     {301, 1}, // 26: rvalue (STR) ->  STR
     {301, 3}, // 27: rvalue ('[') ->  '[' opt_list ']'
     {301, 1}, // 28: rvalue ->  function
     {301, 1}, // 29: rvalue ->  element
     {301, 1}, // 30: rvalue ->  new_array
     {302, 1}, // 31: lvalue (VAR) ->  VAR
     {303, 2}, // 32: element ->  lvalue index
     {304, 3}, // 33: index ('[') ->  '[' expr ']'
     {305, 2}, // 34: new_array (ARRAY) ->  ARRAY CST
     {305, 3}, // 35: new_array (ARRAY) ->  ARRAY CST CST
     {305, 3}, // 36: new_array (ARRAY) ->  ARRAY CST CHR
     {306, 4}, // 37: function (FUNNAME) ->  FUNNAME '(' opt_list ')'
     {307, 1}, // 38: expr ->  lvalue
     {307, 1}, // 39: expr ->  rvalue
     {307, 3}, // 40: expr ('=') ->  lvalue '=' expr
     {307, 3}, // 41: expr (ADD) ->  lvalue ADD expr
     {307, 3}, // 42: expr (SUB) ->  lvalue SUB expr
     {307, 3}, // 43: expr (MUL) ->  lvalue MUL expr
     {307, 3}, // 44: expr (DIV) ->  lvalue DIV expr
     {307, 3}, // 45: expr (MOD) ->  lvalue MOD expr
     {307, 3}, // 46: expr ('=') ->  element '=' expr
     {307, 3}, // 47: expr (ADD) ->  element ADD expr
     {307, 3}, // 48: expr (SUB) ->  element SUB expr
     {307, 3}, // 49: expr (MUL) ->  element MUL expr
     {307, 3}, // 50: expr (DIV) ->  element DIV expr
     {307, 3}, // 51: expr (MOD) ->  element MOD expr
     {307, 3}, // 52: expr ('+') ->  expr '+' expr
     {307, 3}, // 53: expr ('-') ->  expr '-' expr
     {307, 3}, // 54: expr ('*') ->  expr '*' expr
     {307, 3}, // 55: expr ('/') ->  expr '/' expr
     {307, 3}, // 56: expr ('%') ->  expr '%' expr
     {307, 3}, // 57: expr ('<') ->  expr '<' expr
     {307, 3}, // 58: expr ('>') ->  expr '>' expr
     {307, 3}, // 59: expr (LE) ->  expr LE expr
     {307, 3}, // 60: expr (GE) ->  expr GE expr
     {307, 3}, // 61: expr (EQ) ->  expr EQ expr
     {307, 3}, // 62: expr (NE) ->  expr NE expr
     {307, 3}, // 63: expr (AND) ->  expr AND expr
     {307, 3}, // 64: expr (OR) ->  expr OR expr
     {307, 2}, // 65: expr ('!') ->  '!' expr
     {307, 3}, // 66: expr ('(') ->  '(' expr ')'
     {308, 1}, // 67: stmt_list_$ ->  stmt_list
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { DEF_RED}, {  2} },             
    { {     290}, {  1} }, // stmt_list
    { {       0}, { -1} },             
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {           31} },             
    { {       291}, {            2} }, // stmt     
    { {       292}, {            3} }, // io_stmt  
    { {       293}, {            4} }, // expr_stmt
    { {       294}, {            5} }, // if_stmt  
    { {       295}, {            6} }, // for_stmt 
    { {       123}, {            7} }, // '{'      
    { {       271}, {            8} }, // PRINTC   
    { {       272}, {            9} }, // PRINTD   
    { {       273}, {           10} }, // PRINTS   
    { {       274}, {           11} }, // SCAN     
    { {       307}, {           12} }, // expr     
    { {       296}, {           13} }, // if       
    { {       298}, {           14} }, // for      
    { {       302}, {           15} }, // lvalue   
    { {       301}, {           16} }, // rvalue   
    { {       303}, {           17} }, // element  
    { {        33}, {           18} }, // '!'      
    { {        40}, {           19} }, // '('      
    { {       275}, {           20} }, // IF       
    { {       277}, {           21} }, // FOR      
    { {       257}, {           22} }, // VAR      
    { {       260}, {           23} }, // CST      
    { {       261}, {           24} }, // CHR      
    { {       258}, {           25} }, // STR      
    { {        91}, {           26} }, // '['      
    { {       306}, {           27} }, // function 
    { {       305}, {           28} }, // new_array
    { {       259}, {           29} }, // FUNNAME  
    { {       278}, {           30} }, // ARRAY    
    { {     _EOF_}, { PARSE_ACCEPT} },             
    { {         0}, {            0} },             
};

SR__ s_2[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_3[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_5[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_6[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_7[] =
{
    { { DEF_RED}, {  2} },             
    { {     290}, { 31} }, // stmt_list
    { {       0}, { -1} },             
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 32} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 33} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 34} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       302}, { 35} }, // lvalue
    { {       257}, { 22} }, // VAR   
    { {         0}, {  0} },          
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, { 15} },       
    { {        59}, { 36} }, // ';'
    { {        43}, { 37} }, // '+'
    { {        45}, { 38} }, // '-'
    { {        42}, { 39} }, // '*'
    { {        47}, { 40} }, // '/'
    { {        37}, { 41} }, // '%'
    { {        60}, { 42} }, // '<'
    { {        62}, { 43} }, // '>'
    { {       282}, { 44} }, // LE 
    { {       281}, { 45} }, // GE 
    { {       283}, { 46} }, // EQ 
    { {       284}, { 47} }, // NE 
    { {       279}, { 48} }, // AND
    { {       280}, { 49} }, // OR 
    { {         0}, {  0} },       
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, { 30} },             
    { {       291}, { 50} }, // stmt     
    { {       292}, {  3} }, // io_stmt  
    { {       293}, {  4} }, // expr_stmt
    { {       294}, {  5} }, // if_stmt  
    { {       295}, {  6} }, // for_stmt 
    { {       123}, {  7} }, // '{'      
    { {       271}, {  8} }, // PRINTC   
    { {       272}, {  9} }, // PRINTD   
    { {       273}, { 10} }, // PRINTS   
    { {       274}, { 11} }, // SCAN     
    { {       307}, { 12} }, // expr     
    { {       296}, { 13} }, // if       
    { {       298}, { 14} }, // for      
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       275}, { 20} }, // IF       
    { {       277}, { 21} }, // FOR      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, { 30} },             
    { {       291}, { 51} }, // stmt     
    { {       292}, {  3} }, // io_stmt  
    { {       293}, {  4} }, // expr_stmt
    { {       294}, {  5} }, // if_stmt  
    { {       295}, {  6} }, // for_stmt 
    { {       123}, {  7} }, // '{'      
    { {       271}, {  8} }, // PRINTC   
    { {       272}, {  9} }, // PRINTD   
    { {       273}, { 10} }, // PRINTS   
    { {       274}, { 11} }, // SCAN     
    { {       307}, { 12} }, // expr     
    { {       296}, { 13} }, // if       
    { {       298}, { 14} }, // for      
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       275}, { 20} }, // IF       
    { {       277}, { 21} }, // FOR      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_15[] =
{
    { { REQ_DEF}, {   9} },         
    { {      61}, {  52} }, // '='  
    { {     285}, {  53} }, // ADD  
    { {     286}, {  54} }, // SUB  
    { {     287}, {  55} }, // MUL  
    { {     288}, {  56} }, // DIV  
    { {     289}, {  57} }, // MOD  
    { {     304}, {  58} }, // index
    { {      91}, {  59} }, // '['  
    { {       0}, { -38} },         
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_17[] =
{
    { { REQ_DEF}, {   7} },       
    { {      61}, {  60} }, // '='
    { {     285}, {  61} }, // ADD
    { {     286}, {  62} }, // SUB
    { {     287}, {  63} }, // MUL
    { {     288}, {  64} }, // DIV
    { {     289}, {  65} }, // MOD
    { {       0}, { -29} },       
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 66} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 67} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 68} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       302}, { 69} }, // lvalue
    { {       257}, { 22} }, // VAR   
    { {         0}, {  0} },          
};

SR__ s_22[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_23[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_24[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_25[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_26[] =
{
    { { REQ_DEF}, {  18} },             
    { {     299}, {  70} }, // opt_list 
    { {     300}, {  71} }, // list     
    { {     307}, {  72} }, // expr     
    { {     302}, {  15} }, // lvalue   
    { {     301}, {  16} }, // rvalue   
    { {     303}, {  17} }, // element  
    { {      33}, {  18} }, // '!'      
    { {      40}, {  19} }, // '('      
    { {     257}, {  22} }, // VAR      
    { {     260}, {  23} }, // CST      
    { {     261}, {  24} }, // CHR      
    { {     258}, {  25} }, // STR      
    { {      91}, {  26} }, // '['      
    { {     306}, {  27} }, // function 
    { {     305}, {  28} }, // new_array
    { {     259}, {  29} }, // FUNNAME  
    { {     278}, {  30} }, // ARRAY    
    { {       0}, { -21} },             
};

SR__ s_27[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_28[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 73} }, // '('
    { {         0}, {  0} },       
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       260}, { 74} }, // CST
    { {         0}, {  0} },       
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, { 31} },             
    { {       125}, { 75} }, // '}'      
    { {       291}, {  2} }, // stmt     
    { {       292}, {  3} }, // io_stmt  
    { {       293}, {  4} }, // expr_stmt
    { {       294}, {  5} }, // if_stmt  
    { {       295}, {  6} }, // for_stmt 
    { {       123}, {  7} }, // '{'      
    { {       271}, {  8} }, // PRINTC   
    { {       272}, {  9} }, // PRINTD   
    { {       273}, { 10} }, // PRINTS   
    { {       274}, { 11} }, // SCAN     
    { {       307}, { 12} }, // expr     
    { {       296}, { 13} }, // if       
    { {       298}, { 14} }, // for      
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       275}, { 20} }, // IF       
    { {       277}, { 21} }, // FOR      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, { 15} },       
    { {        59}, { 76} }, // ';'
    { {        43}, { 37} }, // '+'
    { {        45}, { 38} }, // '-'
    { {        42}, { 39} }, // '*'
    { {        47}, { 40} }, // '/'
    { {        37}, { 41} }, // '%'
    { {        60}, { 42} }, // '<'
    { {        62}, { 43} }, // '>'
    { {       282}, { 44} }, // LE 
    { {       281}, { 45} }, // GE 
    { {       283}, { 46} }, // EQ 
    { {       284}, { 47} }, // NE 
    { {       279}, { 48} }, // AND
    { {       280}, { 49} }, // OR 
    { {         0}, {  0} },       
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, { 15} },       
    { {        59}, { 77} }, // ';'
    { {        43}, { 37} }, // '+'
    { {        45}, { 38} }, // '-'
    { {        42}, { 39} }, // '*'
    { {        47}, { 40} }, // '/'
    { {        37}, { 41} }, // '%'
    { {        60}, { 42} }, // '<'
    { {        62}, { 43} }, // '>'
    { {       282}, { 44} }, // LE 
    { {       281}, { 45} }, // GE 
    { {       283}, { 46} }, // EQ 
    { {       284}, { 47} }, // NE 
    { {       279}, { 48} }, // AND
    { {       280}, { 49} }, // OR 
    { {         0}, {  0} },       
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, { 15} },       
    { {        59}, { 78} }, // ';'
    { {        43}, { 37} }, // '+'
    { {        45}, { 38} }, // '-'
    { {        42}, { 39} }, // '*'
    { {        47}, { 40} }, // '/'
    { {        37}, { 41} }, // '%'
    { {        60}, { 42} }, // '<'
    { {        62}, { 43} }, // '>'
    { {       282}, { 44} }, // LE 
    { {       281}, { 45} }, // GE 
    { {       283}, { 46} }, // EQ 
    { {       284}, { 47} }, // NE 
    { {       279}, { 48} }, // AND
    { {       280}, { 49} }, // OR 
    { {         0}, {  0} },       
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 79} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_36[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 80} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 81} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 82} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 83} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 84} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 85} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 86} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 87} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 88} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 89} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 90} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 91} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 92} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_50[] =
{
    { { REQ_DEF}, {   3} },        
    { {     297}, {  93} }, // else
    { {     276}, {  94} }, // ELSE
    { {       0}, { -13} },        
};

SR__ s_51[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 95} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 96} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 97} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 98} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, { 16} },             
    { {       307}, { 99} }, // expr     
    { {       302}, { 15} }, // lvalue   
    { {       301}, { 16} }, // rvalue   
    { {       303}, { 17} }, // element  
    { {        33}, { 18} }, // '!'      
    { {        40}, { 19} }, // '('      
    { {       257}, { 22} }, // VAR      
    { {       260}, { 23} }, // CST      
    { {       261}, { 24} }, // CHR      
    { {       258}, { 25} }, // STR      
    { {        91}, { 26} }, // '['      
    { {       306}, { 27} }, // function 
    { {       305}, { 28} }, // new_array
    { {       259}, { 29} }, // FUNNAME  
    { {       278}, { 30} }, // ARRAY    
    { {         0}, {  0} },             
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, {  16} },             
    { {       307}, { 100} }, // expr     
    { {       302}, {  15} }, // lvalue   
    { {       301}, {  16} }, // rvalue   
    { {       303}, {  17} }, // element  
    { {        33}, {  18} }, // '!'      
    { {        40}, {  19} }, // '('      
    { {       257}, {  22} }, // VAR      
    { {       260}, {  23} }, // CST      
    { {       261}, {  24} }, // CHR      
    { {       258}, {  25} }, // STR      
    { {        91}, {  26} }, // '['      
    { {       306}, {  27} }, // function 
    { {       305}, {  28} }, // new_array
    { {       259}, {  29} }, // FUNNAME  
    { {       278}, {  30} }, // ARRAY    
    { {         0}, {   0} },             
};

SR__ s_58[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, {  16} },             
    { {       307}, { 101} }, // expr     
    { {       302}, {  15} }, // lvalue   
    { {       301}, {  16} }, // rvalue   
    { {       303}, {  17} }, // element  
    { {        33}, {  18} }, // '!'      
    { {        40}, {  19} }, // '('      
    { {       257}, {  22} }, // VAR      
    { {       260}, {  23} }, // CST      
    { {       261}, {  24} }, // CHR      
    { {       258}, {  25} }, // STR      
    { {        91}, {  26} }, // '['      
    { {       306}, {  27} }, // function 
    { {       305}, {  28} }, // new_array
    { {       259}, {  29} }, // FUNNAME  
    { {       278}, {  30} }, // ARRAY    
    { {         0}, {   0} },             
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, {  16} },             
    { {       307}, { 102} }, // expr     
    { {       302}, {  15} }, // lvalue   
    { {       301}, {  16} }, // rvalue   
    { {       303}, {  17} }, // element  
    { {        33}, {  18} }, // '!'      
    { {        40}, {  19} }, // '('      
    { {       257}, {  22} }, // VAR      
    { {       260}, {  23} }, // CST      
    { {       261}, {  24} }, // CHR      
    { {       258}, {  25} }, // STR      
    { {        91}, {  26} }, // '['      
    { {       306}, {  27} }, // function 
    { {       305}, {  28} }, // new_array
    { {       259}, {  29} }, // FUNNAME  
    { {       278}, {  30} }, // ARRAY    
    { {         0}, {   0} },             
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, {  16} },             
    { {       307}, { 103} }, // expr     
    { {       302}, {  15} }, // lvalue   
    { {       301}, {  16} }, // rvalue   
    { {       303}, {  17} }, // element  
    { {        33}, {  18} }, // '!'      
    { {        40}, {  19} }, // '('      
    { {       257}, {  22} }, // VAR      
    { {       260}, {  23} }, // CST      
    { {       261}, {  24} }, // CHR      
    { {       258}, {  25} }, // STR      
    { {        91}, {  26} }, // '['      
    { {       306}, {  27} }, // function 
    { {       305}, {  28} }, // new_array
    { {       259}, {  29} }, // FUNNAME  
    { {       278}, {  30} }, // ARRAY    
    { {         0}, {   0} },             
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, {  16} },             
    { {       307}, { 104} }, // expr     
    { {       302}, {  15} }, // lvalue   
    { {       301}, {  16} }, // rvalue   
    { {       303}, {  17} }, // element  
    { {        33}, {  18} }, // '!'      
    { {        40}, {  19} }, // '('      
    { {       257}, {  22} }, // VAR      
    { {       260}, {  23} }, // CST      
    { {       261}, {  24} }, // CHR      
    { {       258}, {  25} }, // STR      
    { {        91}, {  26} }, // '['      
    { {       306}, {  27} }, // function 
    { {       305}, {  28} }, // new_array
    { {       259}, {  29} }, // FUNNAME  
    { {       278}, {  30} }, // ARRAY    
    { {         0}, {   0} },             
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, {  16} },             
    { {       307}, { 105} }, // expr     
    { {       302}, {  15} }, // lvalue   
    { {       301}, {  16} }, // rvalue   
    { {       303}, {  17} }, // element  
    { {        33}, {  18} }, // '!'      
    { {        40}, {  19} }, // '('      
    { {       257}, {  22} }, // VAR      
    { {       260}, {  23} }, // CST      
    { {       261}, {  24} }, // CHR      
    { {       258}, {  25} }, // STR      
    { {        91}, {  26} }, // '['      
    { {       306}, {  27} }, // function 
    { {       305}, {  28} }, // new_array
    { {       259}, {  29} }, // FUNNAME  
    { {       278}, {  30} }, // ARRAY    
    { {         0}, {   0} },             
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, {  16} },             
    { {       307}, { 106} }, // expr     
    { {       302}, {  15} }, // lvalue   
    { {       301}, {  16} }, // rvalue   
    { {       303}, {  17} }, // element  
    { {        33}, {  18} }, // '!'      
    { {        40}, {  19} }, // '('      
    { {       257}, {  22} }, // VAR      
    { {       260}, {  23} }, // CST      
    { {       261}, {  24} }, // CHR      
    { {       258}, {  25} }, // STR      
    { {        91}, {  26} }, // '['      
    { {       306}, {  27} }, // function 
    { {       305}, {  28} }, // new_array
    { {       259}, {  29} }, // FUNNAME  
    { {       278}, {  30} }, // ARRAY    
    { {         0}, {   0} },             
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, {  16} },             
    { {       307}, { 107} }, // expr     
    { {       302}, {  15} }, // lvalue   
    { {       301}, {  16} }, // rvalue   
    { {       303}, {  17} }, // element  
    { {        33}, {  18} }, // '!'      
    { {        40}, {  19} }, // '('      
    { {       257}, {  22} }, // VAR      
    { {       260}, {  23} }, // CST      
    { {       261}, {  24} }, // CHR      
    { {       258}, {  25} }, // STR      
    { {        91}, {  26} }, // '['      
    { {       306}, {  27} }, // function 
    { {       305}, {  28} }, // new_array
    { {       259}, {  29} }, // FUNNAME  
    { {       278}, {  30} }, // ARRAY    
    { {         0}, {   0} },             
};

SR__ s_66[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -65} }, 
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, {  15} },       
    { {        41}, { 108} }, // ')'
    { {        43}, {  37} }, // '+'
    { {        45}, {  38} }, // '-'
    { {        42}, {  39} }, // '*'
    { {        47}, {  40} }, // '/'
    { {        37}, {  41} }, // '%'
    { {        60}, {  42} }, // '<'
    { {        62}, {  43} }, // '>'
    { {       282}, {  44} }, // LE 
    { {       281}, {  45} }, // GE 
    { {       283}, {  46} }, // EQ 
    { {       284}, {  47} }, // NE 
    { {       279}, {  48} }, // AND
    { {       280}, {  49} }, // OR 
    { {         0}, {   0} },       
};

SR__ s_68[] =
{
    { { REQ_DEF}, {  14} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {      60}, {  42} }, // '<'
    { {      62}, {  43} }, // '>'
    { {     282}, {  44} }, // LE 
    { {     281}, {  45} }, // GE 
    { {     283}, {  46} }, // EQ 
    { {     284}, {  47} }, // NE 
    { {     279}, {  48} }, // AND
    { {     280}, {  49} }, // OR 
    { {       0}, { -16} },       
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        61}, { 109} }, // '='
    { {         0}, {   0} },       
};

SR__ s_70[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        93}, { 110} }, // ']'
    { {         0}, {   0} },       
};

SR__ s_71[] =
{
    { { REQ_DEF}, {   2} },       
    { {      44}, { 111} }, // ','
    { {       0}, { -20} },       
};

SR__ s_72[] =
{
    { { REQ_DEF}, {  14} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {      60}, {  42} }, // '<'
    { {      62}, {  43} }, // '>'
    { {     282}, {  44} }, // LE 
    { {     281}, {  45} }, // GE 
    { {     283}, {  46} }, // EQ 
    { {     284}, {  47} }, // NE 
    { {     279}, {  48} }, // AND
    { {     280}, {  49} }, // OR 
    { {       0}, { -22} },       
};

SR__ s_73[] =
{
    { { REQ_DEF}, {  18} },             
    { {     299}, { 112} }, // opt_list 
    { {     300}, {  71} }, // list     
    { {     307}, {  72} }, // expr     
    { {     302}, {  15} }, // lvalue   
    { {     301}, {  16} }, // rvalue   
    { {     303}, {  17} }, // element  
    { {      33}, {  18} }, // '!'      
    { {      40}, {  19} }, // '('      
    { {     257}, {  22} }, // VAR      
    { {     260}, {  23} }, // CST      
    { {     261}, {  24} }, // CHR      
    { {     258}, {  25} }, // STR      
    { {      91}, {  26} }, // '['      
    { {     306}, {  27} }, // function 
    { {     305}, {  28} }, // new_array
    { {     259}, {  29} }, // FUNNAME  
    { {     278}, {  30} }, // ARRAY    
    { {       0}, { -21} },             
};

SR__ s_74[] =
{
    { { REQ_DEF}, {   3} },       
    { {     260}, { 113} }, // CST
    { {     261}, { 114} }, // CHR
    { {       0}, { -34} },       
};

SR__ s_75[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_76[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_77[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_78[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_79[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_80[] =
{
    { { REQ_DEF}, {   4} },       
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {       0}, { -52} },       
};

SR__ s_81[] =
{
    { { REQ_DEF}, {   4} },       
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {       0}, { -53} },       
};

SR__ s_82[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_83[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -55} }, 
};

SR__ s_84[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -56} }, 
};

SR__ s_85[] =
{
    { { REQ_DEF}, {   6} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {       0}, { -57} },       
};

SR__ s_86[] =
{
    { { REQ_DEF}, {   6} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {       0}, { -58} },       
};

SR__ s_87[] =
{
    { { REQ_DEF}, {   6} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {       0}, { -59} },       
};

SR__ s_88[] =
{
    { { REQ_DEF}, {   6} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {       0}, { -60} },       
};

SR__ s_89[] =
{
    { { REQ_DEF}, {   6} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {       0}, { -61} },       
};

SR__ s_90[] =
{
    { { REQ_DEF}, {   6} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {       0}, { -62} },       
};

SR__ s_91[] =
{
    { { REQ_DEF}, {  12} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {      60}, {  42} }, // '<'
    { {      62}, {  43} }, // '>'
    { {     282}, {  44} }, // LE 
    { {     281}, {  45} }, // GE 
    { {     283}, {  46} }, // EQ 
    { {     284}, {  47} }, // NE 
    { {       0}, { -63} },       
};

SR__ s_92[] =
{
    { { REQ_DEF}, {  12} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {      60}, {  42} }, // '<'
    { {      62}, {  43} }, // '>'
    { {     282}, {  44} }, // LE 
    { {     281}, {  45} }, // GE 
    { {     283}, {  46} }, // EQ 
    { {     284}, {  47} }, // NE 
    { {       0}, { -64} },       
};

SR__ s_93[] =
{
    { { REQ_TOKEN}, {  30} },             
    { {       291}, { 115} }, // stmt     
    { {       292}, {   3} }, // io_stmt  
    { {       293}, {   4} }, // expr_stmt
    { {       294}, {   5} }, // if_stmt  
    { {       295}, {   6} }, // for_stmt 
    { {       123}, {   7} }, // '{'      
    { {       271}, {   8} }, // PRINTC   
    { {       272}, {   9} }, // PRINTD   
    { {       273}, {  10} }, // PRINTS   
    { {       274}, {  11} }, // SCAN     
    { {       307}, {  12} }, // expr     
    { {       296}, {  13} }, // if       
    { {       298}, {  14} }, // for      
    { {       302}, {  15} }, // lvalue   
    { {       301}, {  16} }, // rvalue   
    { {       303}, {  17} }, // element  
    { {        33}, {  18} }, // '!'      
    { {        40}, {  19} }, // '('      
    { {       275}, {  20} }, // IF       
    { {       277}, {  21} }, // FOR      
    { {       257}, {  22} }, // VAR      
    { {       260}, {  23} }, // CST      
    { {       261}, {  24} }, // CHR      
    { {       258}, {  25} }, // STR      
    { {        91}, {  26} }, // '['      
    { {       306}, {  27} }, // function 
    { {       305}, {  28} }, // new_array
    { {       259}, {  29} }, // FUNNAME  
    { {       278}, {  30} }, // ARRAY    
    { {         0}, {   0} },             
};

SR__ s_94[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_95[] =
{
    { { REQ_DEF}, {   6} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {       0}, { -40} },       
};

SR__ s_96[] =
{
    { { REQ_DEF}, {   6} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {       0}, { -41} },       
};

SR__ s_97[] =
{
    { { REQ_DEF}, {   6} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {       0}, { -42} },       
};

SR__ s_98[] =
{
    { { REQ_DEF}, {   6} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {       0}, { -43} },       
};

SR__ s_99[] =
{
    { { REQ_DEF}, {   6} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {       0}, { -44} },       
};

SR__ s_100[] =
{
    { { REQ_DEF}, {   6} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {       0}, { -45} },       
};

SR__ s_101[] =
{
    { { REQ_TOKEN}, {  15} },       
    { {        93}, { 116} }, // ']'
    { {        43}, {  37} }, // '+'
    { {        45}, {  38} }, // '-'
    { {        42}, {  39} }, // '*'
    { {        47}, {  40} }, // '/'
    { {        37}, {  41} }, // '%'
    { {        60}, {  42} }, // '<'
    { {        62}, {  43} }, // '>'
    { {       282}, {  44} }, // LE 
    { {       281}, {  45} }, // GE 
    { {       283}, {  46} }, // EQ 
    { {       284}, {  47} }, // NE 
    { {       279}, {  48} }, // AND
    { {       280}, {  49} }, // OR 
    { {         0}, {   0} },       
};

SR__ s_102[] =
{
    { { REQ_DEF}, {   6} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {       0}, { -46} },       
};

SR__ s_103[] =
{
    { { REQ_DEF}, {   6} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {       0}, { -47} },       
};

SR__ s_104[] =
{
    { { REQ_DEF}, {   6} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {       0}, { -48} },       
};

SR__ s_105[] =
{
    { { REQ_DEF}, {   6} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {       0}, { -49} },       
};

SR__ s_106[] =
{
    { { REQ_DEF}, {   6} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {       0}, { -50} },       
};

SR__ s_107[] =
{
    { { REQ_DEF}, {   6} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {       0}, { -51} },       
};

SR__ s_108[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -66} }, 
};

SR__ s_109[] =
{
    { { REQ_TOKEN}, {  16} },             
    { {       307}, { 117} }, // expr     
    { {       302}, {  15} }, // lvalue   
    { {       301}, {  16} }, // rvalue   
    { {       303}, {  17} }, // element  
    { {        33}, {  18} }, // '!'      
    { {        40}, {  19} }, // '('      
    { {       257}, {  22} }, // VAR      
    { {       260}, {  23} }, // CST      
    { {       261}, {  24} }, // CHR      
    { {       258}, {  25} }, // STR      
    { {        91}, {  26} }, // '['      
    { {       306}, {  27} }, // function 
    { {       305}, {  28} }, // new_array
    { {       259}, {  29} }, // FUNNAME  
    { {       278}, {  30} }, // ARRAY    
    { {         0}, {   0} },             
};

SR__ s_110[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_111[] =
{
    { { REQ_TOKEN}, {  16} },             
    { {       307}, { 118} }, // expr     
    { {       302}, {  15} }, // lvalue   
    { {       301}, {  16} }, // rvalue   
    { {       303}, {  17} }, // element  
    { {        33}, {  18} }, // '!'      
    { {        40}, {  19} }, // '('      
    { {       257}, {  22} }, // VAR      
    { {       260}, {  23} }, // CST      
    { {       261}, {  24} }, // CHR      
    { {       258}, {  25} }, // STR      
    { {        91}, {  26} }, // '['      
    { {       306}, {  27} }, // function 
    { {       305}, {  28} }, // new_array
    { {       259}, {  29} }, // FUNNAME  
    { {       278}, {  30} }, // ARRAY    
    { {         0}, {   0} },             
};

SR__ s_112[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 119} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_113[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_114[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_115[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_116[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_117[] =
{
    { { REQ_TOKEN}, {  15} },       
    { {        58}, { 120} }, // ':'
    { {        43}, {  37} }, // '+'
    { {        45}, {  38} }, // '-'
    { {        42}, {  39} }, // '*'
    { {        47}, {  40} }, // '/'
    { {        37}, {  41} }, // '%'
    { {        60}, {  42} }, // '<'
    { {        62}, {  43} }, // '>'
    { {       282}, {  44} }, // LE 
    { {       281}, {  45} }, // GE 
    { {       283}, {  46} }, // EQ 
    { {       284}, {  47} }, // NE 
    { {       279}, {  48} }, // AND
    { {       280}, {  49} }, // OR 
    { {         0}, {   0} },       
};

SR__ s_118[] =
{
    { { REQ_DEF}, {  14} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {      60}, {  42} }, // '<'
    { {      62}, {  43} }, // '>'
    { {     282}, {  44} }, // LE 
    { {     281}, {  45} }, // GE 
    { {     283}, {  46} }, // EQ 
    { {     284}, {  47} }, // NE 
    { {     279}, {  48} }, // AND
    { {     280}, {  49} }, // OR 
    { {       0}, { -23} },       
};

SR__ s_119[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_120[] =
{
    { { REQ_TOKEN}, {  16} },             
    { {       307}, { 121} }, // expr     
    { {       302}, {  15} }, // lvalue   
    { {       301}, {  16} }, // rvalue   
    { {       303}, {  17} }, // element  
    { {        33}, {  18} }, // '!'      
    { {        40}, {  19} }, // '('      
    { {       257}, {  22} }, // VAR      
    { {       260}, {  23} }, // CST      
    { {       261}, {  24} }, // CHR      
    { {       258}, {  25} }, // STR      
    { {        91}, {  26} }, // '['      
    { {       306}, {  27} }, // function 
    { {       305}, {  28} }, // new_array
    { {       259}, {  29} }, // FUNNAME  
    { {       278}, {  30} }, // ARRAY    
    { {         0}, {   0} },             
};

SR__ s_121[] =
{
    { { REQ_DEF}, {  15} },       
    { {      58}, { 122} }, // ':'
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {      60}, {  42} }, // '<'
    { {      62}, {  43} }, // '>'
    { {     282}, {  44} }, // LE 
    { {     281}, {  45} }, // GE 
    { {     283}, {  46} }, // EQ 
    { {     284}, {  47} }, // NE 
    { {     279}, {  48} }, // AND
    { {     280}, {  49} }, // OR 
    { {       0}, { -18} },       
};

SR__ s_122[] =
{
    { { REQ_TOKEN}, {  16} },             
    { {       307}, { 123} }, // expr     
    { {       302}, {  15} }, // lvalue   
    { {       301}, {  16} }, // rvalue   
    { {       303}, {  17} }, // element  
    { {        33}, {  18} }, // '!'      
    { {        40}, {  19} }, // '('      
    { {       257}, {  22} }, // VAR      
    { {       260}, {  23} }, // CST      
    { {       261}, {  24} }, // CHR      
    { {       258}, {  25} }, // STR      
    { {        91}, {  26} }, // '['      
    { {       306}, {  27} }, // function 
    { {       305}, {  28} }, // new_array
    { {       259}, {  29} }, // FUNNAME  
    { {       278}, {  30} }, // ARRAY    
    { {         0}, {   0} },             
};

SR__ s_123[] =
{
    { { REQ_DEF}, {  14} },       
    { {      43}, {  37} }, // '+'
    { {      45}, {  38} }, // '-'
    { {      42}, {  39} }, // '*'
    { {      47}, {  40} }, // '/'
    { {      37}, {  41} }, // '%'
    { {      60}, {  42} }, // '<'
    { {      62}, {  43} }, // '>'
    { {     282}, {  44} }, // LE 
    { {     281}, {  45} }, // GE 
    { {     283}, {  46} }, // EQ 
    { {     284}, {  47} }, // NE 
    { {     279}, {  48} }, // AND
    { {     280}, {  49} }, // OR 
    { {       0}, { -19} },       
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,
};

} // anonymous namespace ends


// $insert namespace-open
namespace Compiler
{

// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 3:
#line 48 "grammar"
        {
         collectGarbage();
         }
        break;

        case 4:
#line 53 "grammar"
        {
         collectGarbage();
         }
        break;

        case 5:
#line 58 "grammar"
        {
         collectGarbage();
         }
        break;

        case 6:
#line 63 "grammar"
        {
         collectGarbage();
         }
        break;

        case 9:
#line 76 "grammar"
        {
         printc(d_vsp__[-1].data<Tag__::INT>()); 
         }
        break;

        case 10:
#line 81 "grammar"
        {
         printd(d_vsp__[-1].data<Tag__::INT>()); 
         }
        break;

        case 11:
#line 86 "grammar"
        {
         prints(d_vsp__[-1].data<Tag__::INT>());
         }
        break;

        case 12:
#line 91 "grammar"
        {
         scan(d_vsp__[-1].data<Tag__::INT>()); 
         }
        break;

        case 13:
#line 98 "grammar"
        {
         stopIf();
         popStack();
         }
        break;

        case 14:
#line 104 "grammar"
        {
         stopIfElse();
         popStack();
         }
        break;

        case 15:
#line 113 "grammar"
        {
         stopFor();
         popStack();
         }
        break;

        case 16:
#line 121 "grammar"
        {
         startIf(d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 17:
#line 129 "grammar"
        {
         startElse();
         }
        break;

        case 18:
#line 136 "grammar"
        {
         startFor(d_vsp__[-4].data<Tag__::INT>(), d_vsp__[-2].data<Tag__::INT>(), -1, d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 19:
#line 141 "grammar"
        {
         startFor(d_vsp__[-6].data<Tag__::INT>(), d_vsp__[-4].data<Tag__::INT>(), d_vsp__[-2].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 21:
#line 150 "grammar"
        {
         d_val__.get<Tag__::LIST>() = std::vector<int>();
         }
        break;

        case 22:
#line 157 "grammar"
        {
         (d_val__.get<Tag__::LIST>()).push_back(d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 23:
#line 162 "grammar"
        {
         (d_val__.get<Tag__::LIST>()).push_back(d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 24:
#line 169 "grammar"
        {
         d_val__.get<Tag__::INT>() = assign(d_vsp__[0].data<Tag__::INT>()); 
         }
        break;

        case 25:
#line 174 "grammar"
        {
         d_val__.get<Tag__::INT>() = assign(d_vsp__[0].data<Tag__::CHAR>());
         }
        break;

        case 26:
#line 179 "grammar"
        {
         d_val__.get<Tag__::INT>() = allocString(d_vsp__[0].data<Tag__::STRING>()); 
         }
        break;

        case 27:
#line 184 "grammar"
        {
         d_val__.get<Tag__::INT>() = allocArray(d_vsp__[-1].data<Tag__::LIST>());
         }
        break;

        case 28:
#line 189 "grammar"
        {
         d_val__.get<Tag__::INT>() = call((d_vsp__[0].data<Tag__::PAIR2>()).first, (d_vsp__[0].data<Tag__::PAIR2>()).second);
         }
        break;

        case 29:
#line 194 "grammar"
        {
         d_val__.get<Tag__::INT>() = arrayValue((d_vsp__[0].data<Tag__::PAIR1>()).first, (d_vsp__[0].data<Tag__::PAIR1>()).second);
         }
        break;

        case 30:
#line 199 "grammar"
        {
         d_val__.get<Tag__::INT>() = d_vsp__[0].data<Tag__::INT>();
         }
        break;

        case 31:
#line 206 "grammar"
        {
         d_val__.get<Tag__::INT>() = allocate(d_vsp__[0].data<Tag__::STRING>());
         }
        break;

        case 32:
#line 213 "grammar"
        {
         d_val__.get<Tag__::PAIR1>() = std::pair<int, int>(d_vsp__[-1].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 33:
#line 220 "grammar"
        {
         d_val__.get<Tag__::INT>() = d_vsp__[-1].data<Tag__::INT>();
         }
        break;

        case 34:
#line 227 "grammar"
        {
         d_val__.get<Tag__::INT>() = allocArray(d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 35:
#line 232 "grammar"
        {
         d_val__.get<Tag__::INT>() = allocArray(d_vsp__[-1].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 36:
#line 237 "grammar"
        {
         d_val__.get<Tag__::INT>() = allocArray(d_vsp__[-1].data<Tag__::INT>(), d_vsp__[0].data<Tag__::CHAR>());
         }
        break;

        case 37:
#line 244 "grammar"
        {
         d_val__.get<Tag__::PAIR2>() = std::pair<std::string, std::vector<int>>(d_vsp__[-3].data<Tag__::STRING>(), d_vsp__[-1].data<Tag__::LIST>());
         }
        break;

        case 40:
#line 255 "grammar"
        {
         d_val__.get<Tag__::INT>() = assign(d_vsp__[-2].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 41:
#line 260 "grammar"
        {
         d_val__.get<Tag__::INT>() = addTo(d_vsp__[-2].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>()); 
         }
        break;

        case 42:
#line 265 "grammar"
        {
         d_val__.get<Tag__::INT>() = subtractFrom(d_vsp__[-2].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 43:
#line 270 "grammar"
        {
         d_val__.get<Tag__::INT>() = multiplyBy(d_vsp__[-2].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>()); 
         }
        break;

        case 44:
#line 275 "grammar"
        {
         d_val__.get<Tag__::INT>() = divideBy(d_vsp__[-2].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>()); 
         }
        break;

        case 45:
#line 280 "grammar"
        {
         d_val__.get<Tag__::INT>() = moduloBy(d_vsp__[-2].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>()); 
         }
        break;

        case 46:
#line 285 "grammar"
        {
         d_val__.get<Tag__::INT>() = assignToElement((d_vsp__[-2].data<Tag__::PAIR1>()).first, (d_vsp__[-2].data<Tag__::PAIR1>()).second, d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 47:
#line 290 "grammar"
        {
         d_val__.get<Tag__::INT>() = addToElement((d_vsp__[-2].data<Tag__::PAIR1>()).first, (d_vsp__[-2].data<Tag__::PAIR1>()).second, d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 48:
#line 295 "grammar"
        {
         d_val__.get<Tag__::INT>() = subtractFromElement((d_vsp__[-2].data<Tag__::PAIR1>()).first, (d_vsp__[-2].data<Tag__::PAIR1>()).second, d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 49:
#line 300 "grammar"
        {
         d_val__.get<Tag__::INT>() = multiplyElement((d_vsp__[-2].data<Tag__::PAIR1>()).first, (d_vsp__[-2].data<Tag__::PAIR1>()).second, d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 50:
#line 305 "grammar"
        {
         d_val__.get<Tag__::INT>() = divideElement((d_vsp__[-2].data<Tag__::PAIR1>()).first, (d_vsp__[-2].data<Tag__::PAIR1>()).second, d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 51:
#line 310 "grammar"
        {
         d_val__.get<Tag__::INT>() = moduloElement((d_vsp__[-2].data<Tag__::PAIR1>()).first, (d_vsp__[-2].data<Tag__::PAIR1>()).second, d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 52:
#line 315 "grammar"
        {
         d_val__.get<Tag__::INT>() = add(d_vsp__[-2].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>()); 
         }
        break;

        case 53:
#line 320 "grammar"
        {
         d_val__.get<Tag__::INT>() = subtract(d_vsp__[-2].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>()); 
         }
        break;

        case 54:
#line 325 "grammar"
        {
         d_val__.get<Tag__::INT>() = multiply(d_vsp__[-2].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>()); 
         }
        break;

        case 55:
#line 330 "grammar"
        {
         d_val__.get<Tag__::INT>() = divide(d_vsp__[-2].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>()); 
         }
        break;

        case 56:
#line 335 "grammar"
        {
         d_val__.get<Tag__::INT>() = modulo(d_vsp__[-2].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>()); 
         }
        break;

        case 57:
#line 340 "grammar"
        {
         d_val__.get<Tag__::INT>() = lt(d_vsp__[-2].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 58:
#line 345 "grammar"
        {
         d_val__.get<Tag__::INT>() = gt(d_vsp__[-2].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 59:
#line 350 "grammar"
        {
         d_val__.get<Tag__::INT>() = le(d_vsp__[-2].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 60:
#line 355 "grammar"
        {
         d_val__.get<Tag__::INT>() = ge(d_vsp__[-2].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 61:
#line 360 "grammar"
        {
         d_val__.get<Tag__::INT>() = eq(d_vsp__[-2].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 62:
#line 365 "grammar"
        {
         d_val__.get<Tag__::INT>() = ne(d_vsp__[-2].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 63:
#line 370 "grammar"
        {
         d_val__.get<Tag__::INT>() = logicAnd(d_vsp__[-2].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 64:
#line 375 "grammar"
        {
         d_val__.get<Tag__::INT>() = logicOr(d_vsp__[-2].data<Tag__::INT>(), d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 65:
#line 380 "grammar"
        {
         d_val__.get<Tag__::INT>() = logicNot(d_vsp__[0].data<Tag__::INT>());
         }
        break;

        case 66:
#line 385 "grammar"
        {
         d_val__.get<Tag__::INT>() = d_vsp__[-1].data<Tag__::INT>();
         }
        break;

    }
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}

// $insert polymorphicImpl
namespace Meta__
{
   Base::~Base()
   {}
}


// $insert namespace-close
}


